### ISSUE TITLE
Decouple staric files

### ISSUE THREAD

**Issue by blacksph3re** [AEGEE/oms-profiles-module#22]
Currently the profiles module serves all the static files it needs like our wrapbootstrap css. These files might also be needed by other parts of the frontend using the same look&feel, so for client side caching purposes all should refer to the same url. 
However, if the service crashes (e. G. Because a user registers) also the static files become unavailable. Thus it would be nice to have them decoupled at some point and served by a nginx or something like that, so this module can crash independently.

**Comment by linuxbandit** [comment]
Do you know how to make a in-house CDN? or, if it has sense at all. What's the best practice solution?

**Comment by blacksph3re** [comment]
Well, I think the key thing about a CDN is that there are many servers and the geologically closest one to the client serves the files. I don't think that we'll be able to spread our servers across the world too soon :D
But well, I'd just set up a nginx to serve some static files? ^^ No magic with that, that's exactly what it made for. Maybe we could use the same nginx to reverse-proxy to the frontends aswell?

**Comment by linuxbandit** [comment]
wowww, alright I didn't imagine a full-fledged CDN :) I just didn't know how to implement other than nginx which sounds perfectly fine

will you do it?

**Comment by blacksph3re** [comment]
Yeah, why not
